= AsciiDoctor Screenshot

This Asciidotor package automate your documentation of your webapp using screenshots.
No more hassles when you change simple settings like CSS or change that button that was too big.
Your documentation stays up to date!

== Quick reference

Basic usage is a block _takeScreenshot_ that points to a URL:

```
[takeScreenshot, url=http://google.com, name=google]
Google Landing page
```

To control the browser (i.e. for filling in a form or doing a login)

```
[driveBrowser]
go "http://google.com"
$("input", name: "q").value("asciidoctor")
waitFor(5){true}
```
=== Parameters

url:: the URL to point to. Optional if previously a page was already screenshoot
name:: an optional unique id (will be generated otherwise), the screenshot will be called `<name>`.png
frame:: Try awesomeness with "IPHONE4", "IPHONE5", "SAMSUNG_S4", "IMAC" or "BROWSER".
dimension:: size of the screenshot for instance 800x600. Also the values of 'frame' are supported. Is ignored if 'frame' is set.
selector:: the CSS-like dom selector to screenshot. Only this will be part of the image. For instance "div #login_window".

=== Examples

```
[takeScreenshot, name=google, url=http://google.com, frame=IMAC]
The Google landing page
```

```
[driveBrowser]
$("input", name: "q").value("asciidoctor")
waitFor(5){true}
```

```
[takeScreenshot, frame=BROWSER]
Some propositions should appear
```

```
[driveBrowser, dimension=IPHONE4]
  $("h3.r a").click()
```

```
[takeScreenshot, frame=SAMSUNG_S4]
Look Ma, it's samsung s4!
```

== Demo

See http://fix.github.io/asciidoctor-screenshot/demo/google.html[Google 101] or http://fix.github.io/asciidoctor-screenshot/demo[Asciidoctor 101].
